### ISSUE TITLE
Tinkering

### ISSUE THREAD

**Issue by adelthesuper** [TheMysticSword/EliteVariety#1]
Yeah its suppose too spawn 3 but spawns like 50...
I recommend a config file too , to edit things like that.

**Comment by TheMysticSword** [comment]
Do you have any mods that make minions gain elite buffs (for example, if you have the blazing aspect, your drones also become blazing)? If so, the Tinkering elites' drones probably also became Tinkering, spawned more drones, and those drones spawned even more drones. Which will be fixed in the next patch.

**Comment by adelthesuper** [comment]
I see understandable, yeah the mods cool but cant do much when it spawns 50 drones everytime. Playing on monsoon auto gives elites to any minions. So its not a mod confliction error , its vanilla.

**Comment by gaforb** [comment]
> I see understandable, yeah the mods cool but cant do much when it spawns 50 drones everytime. Playing on monsoon auto gives elites to any minions. So its not a mod confliction error , its vanilla.

Just wanna weigh in, that is not a feature of vanilla.

**Comment by TheMysticSword** [comment]
Should be fixed in the upcoming patch which will come out today
